name:                AOC2021
version:             0.1.0.0
github:              "b1g3ar5/AOC2021.git"
license:             BSD3
author:              "Nick Straw"
maintainer:          "nick@broxholme.com"
copyright:           "2021 Nick Straw"

default-extensions: ViewPatterns, TupleSections, GADTs, BangPatterns, RankNTypes, TypeApplications, PolyKinds, StandaloneKindSignatures, ExistentialQuantification, TypeOperators, ConstraintKinds, DeriveFoldable, DeriveFunctor, DeriveTraversable, StandaloneDeriving, GeneralisedNewtypeDeriving, DeriveGeneric

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on GitHub at <https://github.com/b1g3ar5/AOC2021/blob/master/README.md>

dependencies:
- base
- timeit
- containers
- unordered-containers
- vector
- split
- Clever
- mtl
- comonad
- sort
- tasty
- tasty-quickcheck
- tasty-hunit
- data-fix
- semirings
- hashable
- adjunctions
- distributive
- vector-space
- Useful
- multiset
- array
- megaparsec
- parser-combinators
- bimap
- memoize
- search-algorithms
- MissingH
- pqueue
- heap
#- grids

library:
  source-dirs: src

executables:
  AOC2021-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -O2
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2021

tests:
  AOC2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2021
